# ~/.config/starship.toml

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$time\
$line_break\
$status\
$character"""

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 4

[cmd_duration]
min_time = 10
show_milliseconds = true
format = "❮ [$duration](bright-black) "

[time]
disabled = false
format = "❮ [$time]($style) "
style = "bright-black"

[python]
disabled = true

[nodejs]
disabled = true

[swift]
disabled = true

