onboarding = false
[theme]
name = "rose-pine-dawn"

[ui]
tab_bar_position = "bottom"

[keys]
split_vertical = "alt+."
new_tab = "alt+,"
previous_tab = "alt+p"
next_tab = "alt+n"
next_workspace = "prefix+ctrl+j"
previous_workspace = "prefix+ctrl+k"
goto = "prefix+ctrl+l"
